[package]
name = "clumsies-desktop"
version = "0.1.0"
edition = "2024"

[lib]
name = "clumsies_desktop_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[[bin]]
name = "clumsies-desktop"
path = "src/main.rs"

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
daemon = { version = "0.1.0", path = "../../../crates/daemon" }
serde = { version = "1", features = ["derive"] }
tauri = { version = "2", features = [] }
