// Static constants that anchor the seed data.
// Dynamic data is generated by faker.zig at runtime.

pub const ORG_ID = "a0000000-0000-0000-0000-000000000001";
pub const ORG_NAME = "acme";
pub const SEED_PASSWORD = "admin";

pub const BASE_MAINTAINER_ID = "usr-seed-maintainer";
pub const BASE_MAINTAINER_USERNAME = "admin";
pub const SEED_USERNAMES = [_][]const u8{
    BASE_MAINTAINER_USERNAME,
    "Dylan",
    "lilhammer",
    "Joji",
    "amimibear",
    "Milo",
    "Nori",
    "Sora",
};
pub const BASE_MEMBER_ID = "usr-seed-member";
pub const BASE_MEMBER_USERNAME = SEED_USERNAMES[1];
pub const BASE_PROMPT_ID = "p-seed-default";
pub const BASE_PROMPT_PATH = "rule/testing/SEED_PUMP.md";
pub const BASE_PROMPT_CONTENT =
    "# SEED_PUMP\n\nSynthetic baseline prompt used by clumsies-seed.\n";
pub const BASE_PROMPT_HASH =
    "sha256:seed000000000000000000000000000000000000000000000000000000000";
pub const BASE_WORKSPACE_ID = "ws-seed-default";
pub const BASE_WORKSPACE_NAME = "seed-sandbox";

pub const ROLES = [_][]const u8{ "maintainer", "member" };
pub const WS_MEMBER_ROLES = [_][]const u8{ "member", "admin" };
pub const PROMPT_PR_STATUSES = [_][]const u8{ "open", "accepted", "rejected" };
pub const CONTEXT_PR_STATUSES = [_][]const u8{ "open", "merged", "rejected" };
pub const TRACE_EVENT_TYPES = [_][]const u8{ "setup", "refer", "refer" };

// Counts for reset mode
pub const USER_COUNT: usize = SEED_USERNAMES.len;
pub const PROMPT_COUNT: usize = 15;
pub const BUNDLE_COUNT: usize = 3;
pub const WORKSPACE_COUNT: usize = 4;
pub const CONTEXT_PR_COUNT: usize = 6;
pub const PROMPT_PR_COUNT: usize = 5;
pub const TRACE_SESSION_COUNT: usize = 8;
pub const TRACE_EVENTS_PER_SESSION: usize = 10;

// Data caps for pump mode (prevents unbounded DB growth)
pub const CAP_TRACE_EVENTS: i64 = 5000;
pub const CAP_CONTEXT_PR_COMMENTS: i64 = 500;
pub const CAP_PROMPT_PR_COMMENTS: i64 = 500;
pub const CAP_PROMPT_PRS: i64 = 200;
pub const CAP_CONTEXT_PRS: i64 = 200;
pub const CAP_CONTEXT_FILES: i64 = 500;
pub const CLEANUP_INTERVAL: u64 = 100;
